//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetParameterEncryptedURLDemo48
{
    public partial class DecryptViewer
    {
        protected global::System.Web.UI.WebControls.Panel pnlNoParams;
        protected global::System.Web.UI.WebControls.Literal litTable;
    }
}
