//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetParameterEncryptedURLDemo48
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.HyperLink hlPatient;
        protected global::System.Web.UI.WebControls.HyperLink hlOrder;
        protected global::System.Web.UI.WebControls.HyperLink hlUser;
        protected global::System.Web.UI.WebControls.HyperLink hlDoc;
        protected global::System.Web.UI.WebControls.HyperLink hlProduct;
        protected global::System.Web.UI.WebControls.HyperLink hlEmployee;
        protected global::System.Web.UI.WebControls.HyperLink hlTicket;
        protected global::System.Web.UI.WebControls.HyperLink hlPayment;
        protected global::System.Web.UI.WebControls.HyperLink hlShipment;
        protected global::System.Web.UI.WebControls.HyperLink hlMulti;
        protected global::System.Web.UI.WebControls.HiddenField hfJsUrl;
        protected global::System.Web.UI.WebControls.HiddenField hfAjaxUrl;
        protected global::System.Web.UI.WebControls.Literal litHtmlAnchor;
    }
}
